"""
rotation/ci/pr_report.py — PR 审计报告生成器

把 CI 结果 → 转成"研究员级别的量化审计报告"
"""
from typing import Dict, List
from datetime import datetime
from .ci_runner import CIGate
from .github_comment import update_or_create_comment, post_comment


def build_researcher_report(result: Dict) -> str:
    """
    构建研究员级别的模型审计报告
    
    Args:
        result: CIGate().result
    
    Returns:
        Markdown 格式的审计报告
    """
    model = result.get("model", "Unknown")
    decision = result.get("decision", "PENDING")
    metrics = result.get("metrics", {})
    drift = result.get("drift", {})
    checks = result.get("checks", {})
    timestamp = result.get("timestamp", datetime.now().isoformat())
    
    # 决策图标
    icon = "✅" if "APPROVED" in decision else "❌"
    
    # Performance section
    perf = _build_performance_section(metrics)
    
    # Signal quality
    signal_quality = _build_signal_quality(metrics)
    
    # Drift analysis
    drift_section = _build_drift_section(drift)
    
    # Key observations (auto-generated insights)
    observations = _build_observations(metrics, checks)
    
    # Decision
    decision_section = _build_decision_section(decision, checks)
    
    report = f"""<!-- CI-REPORT -->

## 📊 Quant CI Report

### 🧠 Model: {model}
**Generated**: {timestamp[:19]}

---

### 📈 Performance

{perf}

---

### 🧭 Signal Quality

{signal_quality}

---

### 🧠 Drift Analysis

{drift_section}

---

### ⚠️ Key Observations

{observations}

---

### 🟢 Decision

{decision_section}

---
*🤖 Auto-generated by CI Gate v2.5 · [GOVERNANCE.md](GOVERNANCE.md)*
"""
    return report


def _build_performance_section(metrics: Dict) -> str:
    """性能指标段"""
    ic = metrics.get("IC", "N/A")
    ic_str = f"{ic:.4f}" if isinstance(ic, (int, float)) else str(ic)
    
    p10 = metrics.get("precision_top10", "N/A")
    p10_str = f"{p10:.2%}" if isinstance(p10, (int, float)) else str(p10)
    
    hit = metrics.get("hit_rate", "N/A")
    hit_str = f"{hit:.2%}" if isinstance(hit, (int, float)) else str(hit)
    
    sharpe = metrics.get("sharpe_proxy", "N/A")
    sharpe_str = f"{sharpe:.2f}" if isinstance(sharpe, (int, float)) else str(sharpe)
    
    mdd = metrics.get("max_drawdown", "N/A")
    mdd_str = f"{mdd:.1%}" if isinstance(mdd, (int, float)) else str(mdd)
    
    alpha = metrics.get("return_over_benchmark", "N/A")
    alpha_str = f"{alpha:+.2%}" if isinstance(alpha, (int, float)) else str(alpha)
    
    recall = metrics.get("recall_main_theme", "N/A")
    recall_str = f"{recall:.1%}" if isinstance(recall, (int, float)) else str(recall)
    
    return f"""| Metric | Value | Interpretation |
|--------|-------|---------------|
| IC (Information Coefficient) | {ic_str} | {'🟢 Strong' if isinstance(ic, (int,float)) and ic > 0.07 else ('🟡 Moderate' if isinstance(ic, (int,float)) and ic > 0.03 else '🔴 Weak')} |
| Precision @ Top 10% | {p10_str} | {'🟢 High' if isinstance(p10, (int,float)) and p10 > 0.6 else '🟡 Acceptable'} |
| Hit Rate (命中率) | {hit_str} | {'🟢 Good' if isinstance(hit, (int,float)) and hit > 0.55 else '🔴 Low'} |
| Sharpe (Proxy) | {sharpe_str} | {'🟢 Strong' if isinstance(sharpe, (int,float)) and sharpe > 1.0 else '🟡 Moderate'} |
| Max Drawdown | {mdd_str} | {'🟢 Safe' if isinstance(mdd, (int,float)) and mdd < 0.15 else '⚠️ Elevated'} |
| Alpha vs Benchmark | {alpha_str} | |
| Recall (主线捕捉率) | {recall_str} | |
"""


def _build_signal_quality(metrics: Dict) -> str:
    """信号质量分析"""
    precision = metrics.get("precision_top10", 0)
    recall = metrics.get("recall_main_theme", 0)
    hit = metrics.get("hit_rate", 0)
    
    # 假阳性率估算
    false_positive = 1.0 - hit if isinstance(hit, (int, float)) and hit > 0 else "N/A"
    fp_str = f"{false_positive:.1%}" if isinstance(false_positive, (int, float)) else str(false_positive)
    
    # 信号稳定性评分
    if isinstance(precision, (int, float)) and precision > 0.6:
        stability = "高 — 信号可靠性强"
    elif isinstance(precision, (int, float)) and precision > 0.45:
        stability = "中等 — 需进一步验证"
    else:
        stability = "低 — 信号噪声较大，建议优化"
    
    return f"""- **主线捕捉率**: {recall:.1%}
- **假阳性率**: {fp_str}
- **Top信号稳定性**: {stability}
"""


def _build_drift_section(drift: Dict) -> str:
    """市场结构漂移分析"""
    score = drift.get("drift_score", 0)
    status = drift.get("drift_status", "unknown")
    alert = drift.get("alert", False)
    
    if alert:
        risk = "⚠️ **预警** — 市场结构出现变化，模型可能需要重新训练"
    elif isinstance(score, (int, float)) and score < 0.1:
        risk = "✅ **安全** — 市场结构与历史一致，模型适用"
    else:
        risk = "🟡 **关注** — 轻微结构变化，持续监控"
    
    details = drift.get("details", {})
    detail_lines = ""
    if details:
        for k, v in details.items():
            detail_lines += f"- {k}: {v}\n"
    
    return f"""- **市场结构状态**: {status}
- **漂移评分**: {score:.3f} (安全范围: <0.15)
- **风险评估**: {risk}
{detail_lines}"""


def _build_observations(metrics: Dict, checks: Dict) -> str:
    """自动生成观察意见"""
    obs = []
    
    # 从指标中提取洞察
    ic = metrics.get("IC", 0)
    precision = metrics.get("precision_top10", 0)
    mdd = metrics.get("max_drawdown", 0)
    
    if isinstance(ic, (int, float)) and ic > 0.07:
        obs.append("- ✅ IC显著为正，模型预测能力有效")
    elif isinstance(ic, (int, float)) and ic < 0.03:
        obs.append("- ⚠️ IC偏低，模型预测力不足，建议检查特征质量")
    
    if isinstance(precision, (int, float)) and precision > 0.6:
        obs.append("- ✅ Top10%信号精度达标，可用于选股决策")
    elif isinstance(precision, (int, float)) and precision < 0.45:
        obs.append("- ⚠️ Top10%精度不足，模型输出噪声较大")
    
    if isinstance(mdd, (int, float)) and mdd > 0.2:
        obs.append("- ⚠️ 最大回撤超过20%，风险控制需加强")
    
    # 从检查项提取
    failed = [k for k, v in checks.items() if not v.get("pass")]
    if failed:
        obs.append(f"- 🔴 **失败项**: {', '.join(failed)} — 必须修复后才能上线")
    
    if not obs:
        obs.append("- 🟢 所有指标正常，无特殊观察")
    
    return "\n".join(obs)


def _build_decision_section(decision: str, checks: Dict) -> str:
    """决策段"""
    if not checks:
        return f"{decision}\n\n> 无检查项数据"
    
    failed = [k for k, v in checks.items() if not v.get("pass")]
    all_pass = len(failed) == 0
    
    if all_pass:
        return f"""{decision}

> 所有指标达标。模型可以合并并上线到日报系统。"""
    else:
        return f"""{decision}

> **失败原因**: {' / '.join(failed)}  
> **修复建议**: 检查特征质量、调整阈值、或增加训练数据。修复后重新提交触发 CI。"""


# ============================================================
# GitHub Actions 入口
# ============================================================

def main():
    """CI → PR Report 主流程 (由 GitHub Actions 调用)"""
    import sys
    
    print("🧠 CI PR Report Generator")
    print("=" * 50)
    
    # 检查是否在 PR 环境
    from .github_comment import get_pr_number
    pr_number = get_pr_number()
    
    if not pr_number:
        print("⚠️ 非 PR 环境，生成本地报告")
        # 本地模式: 只生成不发布
        return
    
    print(f"📝 PR #{pr_number} — 生成审计报告...")
    
    # 从最近的 CI 结果加载
    import os, json
    report_dir = os.path.join(os.path.dirname(__file__), "reports")
    reports = sorted([f for f in os.listdir(report_dir) if f.endswith('.json')], reverse=True) if os.path.exists(report_dir) else []
    
    if not reports:
        print("⚠️ 无 CI 报告可用")
        return
    
    # 加载最新报告
    with open(os.path.join(report_dir, reports[0])) as f:
        ci_result = json.load(f)
    
    # 生成研究员报告
    report = build_researcher_report(ci_result)
    
    # 发布到 PR
    result = update_or_create_comment(report, pr_number)
    
    if result.get("posted"):
        print(f"✅ 审计报告已发布到 PR #{pr_number}")
    else:
        print(f"❌ 发布失败: {result.get('error', 'unknown')}")


if __name__ == "__main__":
    main()
