"""
rotation/evolution/timeline.py — 时间序列进化曲线 + 进化报告
"""
import os
from datetime import datetime
from .log_store import read_all_records
from .analyzer import analyze_trend, generate_evolution_summary
from .diff import find_best_improvement, find_worst_regression, find_best_version

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
REPORT_DIR = os.path.join(ROOT, "rotation", "evolution", "reports")
os.makedirs(REPORT_DIR, exist_ok=True)


def generate_evolution_report() -> str:
    """生成完整进化报告 Markdown"""
    records = read_all_records()
    trend = analyze_trend()
    best_imp = find_best_improvement()
    worst_reg = find_worst_regression()
    best_ver = find_best_version()
    
    lines = [
        f"# 🧬 Model Evolution Report",
        f"",
        f"**Generated**: {datetime.now().strftime('%Y-%m-%d %H:%M')}",
        f"**Total Versions**: {len(records)}",
        f"",
        f"---",
        f"",
        f"## 📈 Performance Change",
        f"",
    ]
    
    if len(records) >= 2:
        latest = records[-1]
        prev = records[-2]
        ic_d = latest["ic"] - prev["ic"]
        p_d = latest["precision_top10"] - prev["precision_top10"]
        lines.append(f"- IC: {latest['ic']:.4f} ({ic_d:+.4f} vs prev)")
        lines.append(f"- Precision: {latest['precision_top10']:.4f} ({p_d:+.4f} vs prev)")
    
    lines.extend([
        f"",
        f"### Trend",
        f"- IC: {trend.get('ic_trend', 'N/A')}",
        f"- Precision: {trend.get('precision_trend', 'N/A')}",
        f"- CI Pass Rate: {trend.get('ci_pass_rate', 0):.0%}",
    ])
    
    # Plateau
    if trend.get("plateau_detected"):
        lines.append(f"")
        lines.append(f"### ⚠️ Plateau Detected")
        lines.append(f"模型进入平台期，IC增长停滞。建议: 尝试新特征或调整模型结构。")
    
    # Best improvement
    if best_imp and "error" not in best_imp:
        lines.extend([
            f"",
            f"### 🏆 Best Improvement",
            f"- {best_imp['from_version']} → {best_imp['to_version']}",
            f"- IC gain: +{best_imp['ic_gain']:.4f}",
            f"- Change: {best_imp.get('change', 'N/A')[:80]}",
        ])
    
    # Worst regression
    if worst_reg and "error" not in worst_reg:
        lines.extend([
            f"",
            f"### 📉 Worst Regression",
            f"- {worst_reg['from_version']} → {worst_reg['to_version']}",
            f"- IC drop: -{worst_reg['ic_drop']:.4f}",
            f"- Change: {worst_reg.get('change', 'N/A')[:80]}",
        ])
    
    # Best version
    if best_ver and "error" not in best_ver:
        lines.extend([
            f"",
            f"### ⭐ Best Version Ever",
            f"- {best_ver['version']} (IC={best_ver['ic']:.4f})",
        ])
    
    # Timeline
    lines.extend([
        f"",
        f"---",
        f"### 📊 Evolution Timeline",
        f"",
        f"| Version | IC | Precision | CI | Drift | Change |",
        f"|---------|-----|-----------|-----|-------|--------|",
    ])
    
    for r in records:
        ci = "✅" if r.get("ci_pass") else "❌"
        lines.append(
            f"| {r['model_version']} | {r['ic']:.4f} | {r['precision_top10']:.4f} | {ci} | {r.get('drift_score',0):.3f} | {r.get('change_summary','')[:40]} |"
        )
    
    lines.extend([
        f"",
        f"---",
        f"*🤖 Auto-generated by Evolution Log System v1 · {datetime.now().strftime('%Y-%m-%d %H:%M')}*",
    ])
    
    report = "\n".join(lines)
    
    # Save
    path = os.path.join(REPORT_DIR, "evolution_report.md")
    with open(path, 'w') as f:
        f.write(report)
    
    return report
